version: "3.3"
services:
  app:
    image: node:12.18.4
    working_dir: /app
    command: yarn start
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server
    env_file: .env
    ports:
      - 1433:1433
